[package]
name = "gtk-rs-tutorial"
version = "0.1.0"
authors = ["Chris Allen <cma@bitemyapp.com>"]

[dependencies]
gtk = "0.2.0"
glib = "^0"
gdk = "^0"
gdk-pixbuf = "^0"
pango = "^0"
cairo-rs = { version = "^0", features = ["png"] }
